### ISSUE TITLE
WebViewJavascriptBridge冲突

### ISSUE THREAD

**Issue by jifengchao** [ChellyLau/MMWebView#1]
与WebViewJavascriptBridge(https://github.com/marcuswestin/WebViewJavascriptBridge)冲突, 代理监听失败

**Comment by ChellyLau** [comment]
确实冲突，代理冲突，不能和WebViewJavascriptBridge一起使用。。直接使用WKWebView吧。🤦‍♀️

**Comment by ChellyLau** [comment]
> 与WebViewJavascriptBridge([https://github.com/marcuswestin/WebViewJavascriptBridge)冲突](https://github.com/marcuswestin/WebViewJavascriptBridge)%E5%86%B2%E7%AA%81), 代理监听失败

确实存在代理冲突，新版本加入了WebViewJavascriptBridge，欢迎使用新版本。😊😊
